version: '3'
services:
  # app:
  #   container_name: app
  #   restart: always
  #   build: .
  #   ports:
  #     - '4000:4000'
  #   external_links:
  #     - rabbitmq
  rabbitmq:
    container_name: rabbitmq-server
    image: rabbitmq:3.8.9
    ports:
      - '15672:15672'
      - '5672:5672'
